module octopus_mq {

    module dds {

        typedef sequence<char> message_payload;

        @topic
        struct message {
            unsigned long hash;
            string mqtt_topic;
            string mqtt_client_id;
            message_payload data;
            long data_size;
        };

    };

};
