module octopus_mq {
    module dds {
        typedef sequence<char> message_payload;

        @topic struct mqtt_message {
            string mqtt_client_id;
            unsigned long hash;
            message_payload data;
            long data_size;
        };
    };
};
